version: '3.1'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Welcome!
      MYSQL_DATABASE: drifty
      MYSQL_USER: dr440127
      MYSQL_PASSWORD: Welcome2!
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - '8081:80'
    restart: always

  matomo:
    image: matomo:latest
    depends_on:
      - db
    ports:
      - '8082:80'
    volumes:
      - matomo_data:/var/www/html
    restart: always

volumes:
  db_data:
  matomo_data:
